{% set version = "master" %}

package:
  name: opensfm
  version: {{ version }}

source:
  fn: opensfm-{{ version }}.tar.gz
  url: https://github.com/OpenDroneMap/OpenSfM/archive/{{ version }}.tar.gz
  sha256: 9eeea7e0f7435985b1010c463bc08fbf03e2112c9fbe07f458283168186dc5c5
  patches:
    - numpy.patch

build:
    number: 0
    features:
      - feature_cuda_{{ cuda_impl }}
      - feature_blas_{{ blas_impl }}

requirements:
  build:
    # - {{ compiler("c") }}
    # - {{ compiler("cxx") }}
    - cmake
    - ninja
  host:
    - python
    - networkx
    - numpy
    - pyproj
    - pytest
    - python-dateutil
    - PyYAML
    - repoze.lru
    - scipy
    - six
    - xmltodict
    - eigen {{ eigen }}
    - suitesparse {{ suitesparse }}
    - ceres {{ ceres }}
    - boost
    - opencv {{ opencv }}
  run:
    - feature_blas {{ feature_blas }} {{ blas_impl }}
    - feature_cuda {{ feature_cuda }} {{ cuda_impl }}
    - glog
    - suitesparse {{ suitesparse }}
    - boost
    - opencv {{ opencv }}
    - python
    - numpy
    - networkx
    - pyproj
    - PyYAML
    - repoze.lru
    - scipy
    - six
    - xmltodict
    - opengv {{ opengv }}

test:
  imports:
    - opensfm.csfm

about:
  home: https://github.com/mapillary/OpenSfM
  license: BSD
  summary: Open source Structure from Motion pipeline

extra:
  recipe-maintainers:
    - v-turin
